### ISSUE TITLE
FIAT requires Caffe?

### ISSUE THREAD

**Issue by jeremydouglass** [christopher5106/FastAnnotationTool#1]
The project documentation says "Requires OPENCV and Google Protobuf."

Does FIAT require Caffe as well?
-  The current default Makefile.config.example sets CAFFE, implying yes
-  Makefile line 35 options `ifdef CAFFE`, implying no 
-  But running Make with a blank Makefile.config (no CAFFE set) errors out:

```
In file included from src/Output.cpp:1:
src/Output.h:23:10: fatal error: 'caffe/proto/caffe.pb.h' file not found
   #include "caffe/proto/caffe.pb.h"
            ^
```

This appears to be because CAFFE_ (a different variable with an underscore) is manually set on Makefile 48 and then checked on Output.h

```
$(compiler) -DCAFFE_=1 -o bin/extractRect $(opencv_flags) $(utils) $(caffe_include) src/Output.cpp src/extractRect.cpp $(opencv_lib) $(caffe_lib) -llmdb $(lgflags)
```

I'm hoping to install FIAT without Caffe if possible -- the barrier to Caffe installation can be quite high on some machines, and it isn't clear to me why it should be a requirement for this tool.

**Comment by christopher5106** [comment]
No. In that case, just comment the line defining CAFFE in Makefile.config.

I just committed a correction. Thanks !
