### ISSUE TITLE
Does FIAT require OpenCV 2 or 3 -- or both?

### ISSUE THREAD

**Issue by jeremydouglass** [christopher5106/FastAnnotationTool#2]
Does FIAT requires OpenCV 2, 3 -- or both? It isn't clear from documentation, configuration, or installation errors when attempting to install FIAT.
1. Documentation says "OPENCV"
2. Errors when attempting to `make` on a machine without OpenCV installed seem to reference OpenCV2: 
   
   ```
   In file included from src/WorkImage.cpp:1:
   src/WorkImage.h:9:10: error: 'opencv2/core/core.hpp' file not found with
        <angled> include; use "quotes" instead
   #include <opencv2/core/core.hpp>
   ```
3. Makefile indicates OpenCV3:
   
   ```
   opencv_lib := -L/usr/local/opt/opencv3/lib $(opencv_l)
   ```
4. Installing first OpenCV3 (e.g. with homebrew on OS X 10.10) then attempting to make FIAT, make gives an error in not finding opencv_contrib:
   
   ```
   ld: library not found for -lopencv_contrib
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [all] Error 1
   ```

...I thought (?) opencv_contrib was included in opencv2 but moved out of opencv3), so this seems to indicate expecting OpenCV2...?

**Comment by christopher5106** [comment]
I commited a correction also. Can you please pull ?
